apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pkgsite.fullname" . }}
  labels:
    {{- include "pkgsite.labels" . | nindent 4 }}
data:
  packages: |
    {{- range $.Values.seed.packages }}
    {{ . }}
    {{- end }}
